name: Daily GitHub Traffic Analysis

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  analyze-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyGithub python-dotenv

      - name: Run main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python main.py

      - name: Run verify.py
        run: |
          python verify.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changes
        run: |
          git add .

      - name: Commit changes
        run: |
          git commit -m "chore: update traffic analysis data [skip ci]" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
